name: deploy

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dep
        uses: bahmutov/npm-install@v1
        with:
          working-directory: |
            server
            client
            launcher

      - name: Build images
        run: docker build ./launcher --no-cache -t ${{secrets.IMAGE_NODE}}

      # - name: Run Tests
      #   run: npm run test --prefix client && npm run test --prefix server

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Launcher Deployer
        #  Only deploy main branch on pushes
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd app
            git pull
            cd launcher
            npm install
            docker build . --no-cache -t ${{secrets.IMAGE_NODE}}
            cd ..
            npm run launcher:prod

      - name: Server/Client Deploy
        #  Only deploy main branch on pushes
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_CLIENT_HOST }}
          username: ${{ secrets.SSH_CLIENT_USERNAME }}
          key: ${{secrets.SSH_CLIENT_KEY}}
          script: |
            source ~/.bashrc
            cd app
            git pull
            cd client
            npm install
            npm run build
            cd ..
            cd server
            npm install
            npm run production
