name: deploy

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dep
        uses: bahmutov/npm-install@v1
        with:
          working-directory: |
            server
            client
            launcher

      - name: Build images
        run: docker build ./launcher --no-cache -t ${{secrets.IMAGE_NODE}}

      - name: Test
        run: npm run test --prefix client && npm run test --prefix server
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Digital Ocean deploy
        #  Only deploy main branch on pushes
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{secrets.SSH_KEY}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}
          script: |
            cd app
            git pull
            cd launcher
            npm install
            docker build . --no-cache -t ${{secrets.IMAGE_NODE}}
            cd ..
            npm run launcher:prod

      - name: Heroku Deploy
        #  Only deploy main branch on pushes
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        env:
          # "HD_" is removed by akhileshns/heroku-deploy
          HD_DB_URI: ${{secrets.DB_URI}}
          HD_CONSUMER_QUEUE: ${{secrets.CONSUMER_QUEUE}}
          HD_PRODUCER_QUEUE: ${{secrets.PRODUCER_QUEUE}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
          HD_RABBITMQ_URL: ${{secrets.RABBITMQ_URL}}
          HD_GITHUB_ID: ${{secrets.GH_ID}}
          HD_GITHUB_SECRET: ${{secrets.GH_SECRET}}
          HD_GITHUB_CALLBACK: ${{secrets.GH_CALLBACK}}

          # Skip husky and cypress install on heroku
          HD_HUSKY_SKIP_INSTALL: "1"
          HD_CYPRESS_INSTALL_BINARY: 0

        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "codingpair" # Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
